vim.keymap.set('n', '<C-a>t', ":$tabnew<CR>", { desc = 'create [t]ab' })
vim.keymap.set('n', '<C-a><Tab>', ":+tabnext<CR>", { desc = 'next <TAB>' })
vim.keymap.set('n', '<C-a><S-Tab>', ":-tabnext<CR>", { desc = 'previou<S-TAB>' })
vim.keymap.set('n', '<C-a>c', ":new<CR>", { desc = '[n]ew buffer' })
vim.keymap.set('n', '<C-a>n', ":bn<CR>", { desc = 'next buffer' })
vim.keymap.set('n', '<C-a>x', ":bd<CR>", { desc = 'close buffer' })
